version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: university_events_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: university_events
    volumes:
      - mongo-data:/data/db
    networks:
      - university-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: university_events_backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/university_events?authSource=admin
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - JWT_EXPIRE=7d
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_email_password
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - university-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: university_events_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - university-network
    stdin_open: true
    tty: true

volumes:
  mongo-data:

networks:
  university-network:
    driver: bridge