version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: university_events_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: university_events
    volumes:
      - mongo-data:/data/db
    networks:
      - university-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: university_events_backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - university-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: university_events_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - university-network
    stdin_open: true
    tty: true

volumes:
  mongo-data:

networks:
  university-network:
    driver: bridge
